node() {
    properties([
        parameters([
            string(defaultValue: "Develop", description: '', name: 'branch'),
            string(defaultValue: "HGZ", description: '', name: 'zone'),
            string(defaultValue: "", description: '', name: 'release'),
            string(defaultValue: "", description: '', name: 'sg'),
            string(defaultValue: "", description: '', name: 'testline')
        ])
    ])

    stage("Checkout source") {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/KevinCIT/Configuration.git']]])
    }

    stage("Create jobs and folders") {
        sh "ls && pwd"

        def branch = env.branch ? env.branch : ''
        def zone = env.zone ? env.zone : ''
        def release = env.release ? env.release : ''
        def sg = env.sg ? env.sg : ''
        def testline = env.testline ? env.testline : ''
        
        echo "branch: ${branch}"
        echo "zone: ${zone}"
        echo "release: ${release}"
        echo "sg: ${sg}"
        echo "testline: ${testline}"

        sh " find . | grep ${branch} | grep ${zone} | grep ${release} | grep ${sg} | grep ${testline}"
    }
}