node() {
    properties([
        parameters([
            string(defaultValue: "HGZ", description: '', name: 'zone'),
            string(defaultValue: "", description: '', name: 'release'),
            string(defaultValue: "", description: '', name: 'sg'),
            string(defaultValue: "", description: '', name: 'testline')
        ])
    ])

    stage("Create jobs and folders") {
        sh "ls && pwd"
        sh "find ."
    }
}